<?php
    global $baseView;
    $erro = $baseView->get('erro');
    $dadosPostados = $baseView->get('dadosPostados');
 
    if (isset($erro)) {
    	$erro = erroStringParaAlert($erro);
?>
        <script>
            alert("<?php echo $erro; ?>");
        </script>
<?php
    }  
?>
<form method="post">
    <div>
        <div>
            Nome:
        </div>
        <div>
            <input type="text" name="nome" value="<?php if (isset($dadosPostados['nome'])) echo $dadosPostados['nome']; ?>" />
        </div>
    </div>
    <div>
        <div>
            NIS:
        </div>
        <div>
            <input type="text" name="nis" value="<?php if (isset($dadosPostados['nis'])) echo $dadosPostados['nis']; ?>" />
        </div>
    </div>
    <div>
        <div>
            E-mail:
        </div>
        <div>
            <input type="text" name="email" value="<?php if (isset($dadosPostados['email'])) echo $dadosPostados['email']; ?>"  />
        </div>
    </div>

    <div>
        <div>
            Telefone:
        </div>
        <div>
            <input type="text" name="telefone" value="<?php if (isset($dadosPostados['telefone'])) echo $dadosPostados['telefone']; ?>" />
        </div>
    </div>

    <div>
        <div>
            <br />
            <input type="submit" name="cmdEnviar" value="Enviar" />
	    <input type="submit" name="cmdEnviar" value="Listagem" />
        </div>
    </div>
</form>
